### ISSUE TITLE
'ProtoParser' object has no attribute 'literalNames'

### ISSUE THREAD

**Issue by abhi1010** [vak/protobuf2uml#6]
Getting an error while running `protobuf2uml/protobuf/main.py`. 

```log
Traceback (most recent call last):
  File "~/protobuf2uml/bin/protobuf/ProtoParser.py", line 545, in proto
    self._errHandler.sync(self)
  File "~/.virtualenvs/ve/lib/python3.6/site-packages/antlr4/error/ErrorStrategy.py", line 220, in sync
Warning: syntax ambiguity - badly delimited number '4.7.' in line 19 of <stdin> splits into two tokens
Error: <stdin>: syntax error in line 19 near '!'
    raise InputMismatchException(recognizer)
antlr4.error.Errors.InputMismatchException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/protobuf2uml/protobuf/main.py", line 156, in <module>
    cli_main()
  File "~/protobuf2uml/protobuf/main.py", line 153, in cli_main
    ostream=sys.stdout)
  File "~/protobuf2uml/protobuf/main.py", line 139, in non_cli_main
    ostream=ostream)
  File "~/protobuf2uml/protobuf/main.py", line 130, in __init__
    self._tree = parser.proto()
  File "~/protobuf2uml/bin/protobuf/ProtoParser.py", line 589, in proto
    self._errHandler.reportError(self, re)
  File "~/.virtualenvs/ve/lib/python3.6/site-packages/antlr4/error/ErrorStrategy.py", line 126, in reportError
    self.reportInputMismatch(recognizer, e)
  File "~/.virtualenvs/ve/lib/python3.6/site-packages/antlr4/error/ErrorStrategy.py", line 263, in reportInputMismatch
    + " expecting " + e.getExpectedTokens().toString(recognizer.literalNames, recognizer.symbolicNames)
AttributeError: 'ProtoParser' object has no attribute 'literalNames'

```

Issue has also been reported by others.

**Comment by georgasa** [comment]
the same here :(
